### ISSUE TITLE
大神现在状况

### ISSUE THREAD

**Issue by junbo-hu** [Wangzhike/HIT-Linux-0.11#2]
大神，研究完这个，你的后续学习计划是什么？目前从事哪方面工作呢？

**Comment by junbo-hu** [comment]
可以加微信交流一下不？

**Comment by Wangzhike** [comment]
@junbo-hu 我还有后面两部分课程没学习，今年研二需要找工作，不知道接下来半年是否有时间把这个课程及实验结束。
我微信：zhike186137，水平一般，欢迎交流！
